framework:
    messenger:
        default_bus: messenger.bus.command
        buses:
            messenger.bus.command:
            messenger.bus.query:
            
        transports:
            sync: 'sync://'
        
        routing:
            Shared\Domain\IBus\ICommand\CommandInterface: sync


        
        

