imports:
    - { resource: 'rabbit_parameters.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        

    Shared\Domain\IService\:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true
        resource: "../src/Domain/IService/"


    Shared\Domain\IBus\:
      resource: "../src/Domain/IBus/"

    
    
    # Register all files from Shared/Infrastructure/
    Shared\Infrastructure\:
     autowire: true      # Automatically injects dependencies in your services.
     autoconfigure: true
     resource: "../src/Infrastructure/"
    


   
            
   
    



  
    

    