imports:
    - { resource: '../../../Shared/config/services.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    _instanceof:
        Shared\Domain\IBus\ICommand\CommandHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.command }

        Shared\Domain\IBus\IQuery\QueryHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.query }
            
    Shared\Application\TokenListener\TokenExpirationListener:
          public: true
          # autowire: true      # Automatically injects dependencies in your services.
          class: Shared\Application\TokenListener\TokenExpirationListener
          tags:

              - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
              - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_authenticated, method: onAuthenticatedAccess }
              - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onTokenExpires }
       

    Shared\Infrastructure\Bus\Command\CommandBus:
        arguments:
          - '@messenger.bus.command'

    Shared\Infrastructure\Bus\Query\QueryBus:
        arguments:
          - '@messenger.bus.query'
      
    
    UserService\:
        resource: '../src/'

